# Generated by Django 3.2 on 2021-04-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_nm', models.CharField(max_length=100)),
                ('invoiceId', models.CharField(max_length=100)),
                ('product_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, null=True)),
                ('weight', models.IntegerField()),
                ('delivery_charge', models.IntegerField()),
                ('cod_charge', models.IntegerField()),
                ('return_charge', models.IntegerField()),
            ],
        ),
    ]
