# Generated by Django 3.2 on 2021-04-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courierParcelApp', '0003_company_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
