# Generated by Django 3.2 on 2021-04-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courierParcelApp', '0009_alter_order_merchant_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cod_charge',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_charge',
            field=models.IntegerField(blank=True),
        ),
    ]
